In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import socket
import glob
import numpy as np

from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [3]:
df = []
df.append(pd.read_csv('/content/drive/MyDrive/Colab Notebooks/only_malware_ad_sc_ran.csv'))
df = pd.concat(df, ignore_index=True)
df = df.drop(['Unnamed: 0'],axis=1)
df = df.dropna()

df.head(10)


Source Port   Destination Port   Protocol   Flow Duration  \
0           443              57050        6.0              15   
1         57050                443        6.0           10067   
2         50481              40019        6.0           45658   
3         60517                443        6.0           50235   
4         54219                443        6.0           50260   
5         56696                443        6.0           50282   
6         55083                443        6.0           50354   
7         48664                443        6.0           50703   
8         56349              12350        6.0          119911   
9         52297                443        6.0           37712   

    Total Fwd Packets   Total Backward Packets  Total Length of Fwd Packets  \
0                   2                        0                         42.0   
1                   3                        0                         42.0   
2                   1                        1                          0.0   
3                   1                        1                          0.0   
4                   1                        1                          0.0   
5                   1                        1                          0.0   
6                   1                        2                          0.0   
7                   1                        1                          0.0   
8                   1                        1                          0.0   
9                   1                        1                         31.0   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                           0.0                    42.0   
1                           0.0                    42.0   
2                           0.0                     0.0   
3                           0.0                     0.0   
4                           0.0                     0.0   
5                           0.0                     0.0   
6                           0.0                     0.0   
7                           0.0                     0.0   
8                           0.0                     0.0   
9                           0.0                    31.0   

    Fwd Packet Length Min  ...   min_seg_size_forward  Active Mean  \
0                     0.0  ...                   32.0          0.0   
1                     0.0  ...                   32.0          0.0   
2                     0.0  ...                   32.0          0.0   
3                     0.0  ...                   32.0          0.0   
4                     0.0  ...                   32.0          0.0   
5                     0.0  ...                   32.0          0.0   
6                     0.0  ...                   32.0          0.0   
7                     0.0  ...                   32.0          0.0   
8                     0.0  ...                   32.0          0.0   
9                    31.0  ...                   32.0          0.0   

    Active Std   Active Max   Active Min  Idle Mean   Idle Std   Idle Max  \
0          0.0          0.0          0.0        0.0        0.0        0.0   
1          0.0          0.0          0.0        0.0        0.0        0.0   
2          0.0          0.0          0.0        0.0        0.0        0.0   
3          0.0          0.0          0.0        0.0        0.0        0.0   
4          0.0          0.0          0.0        0.0        0.0        0.0   
5          0.0          0.0          0.0        0.0        0.0        0.0   
6          0.0          0.0          0.0        0.0        0.0        0.0   
7          0.0          0.0          0.0        0.0        0.0        0.0   
8          0.0          0.0          0.0        0.0        0.0        0.0   
9          0.0          0.0          0.0        0.0        0.0        0.0   

    Idle Min   Label  
0        0.0  ADWARE  
1        0.0  ADWARE  
2        0.0  ADWARE  
3        0.0  ADWARE  
4        0.0  ADWARE  
5        0.

In [4]:
print(df[' Label'].unique())

['ADWARE' 'SCAREWARE' 'RANSOMWARE']


In [5]:
#zmiana etykiet na liczby

le = LabelEncoder() #przekształca etykiety nienumeryczne w 'Label' na numeryczne
df[' Label'] = le.fit_transform(df[' Label'])

print(df[' Label'].unique())

[0 2 1]


In [6]:
X = df.drop([' Label'],axis=1) #dzielimy dane train/test
y = df[' Label']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

y_pred = dt.predict(X_test)

dt.score(X_test, y_test)

0.6345081738906863

In [8]:
print("Matrix:")
print(confusion_matrix(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
tp, fn, fp, tn = confusion_matrix(y_test, y_pred, labels=[1,0]).ravel()
sensitivity = tp/(tp+fn)
specificity = tn/(fp+tn)
print("accuracy = ", acc)
print("sensitivity = ", sensitivity)
print("specificity = ", specificity)

Matrix:
[[53665 11436 19697]
 [11509 45854 12384]
 [18593 11674 48553]]
accuracy =  0.6345081738906863
sensitivity =  0.7993654446245838
specificity =  0.8243344956298675


In [11]:
import graphviz
from sklearn import tree

dot_data = tree.export_graphviz(dt, max_depth=3, feature_names=X_train.columns) 
#dot_data = tree.export_graphviz(dt, max_depth=3) 

graph = graphviz.Source(dot_data) 
graph
graph.render(filename='/content/drive/MyDrive/Colab Notebooks/drzewo_decyzyjne_2')

'/content/drive/MyDrive/Colab Notebooks/drzewo_decyzyjne_2.pdf'

KONIEC